# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadgen < Formula
  desc "Load generator for Aforo NextGen — multi-tenant SaaS billing & metering platform."
  homepage "https://github.com/aforoai/aforo-nextgen-loadgen"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aforoai/aforo-nextgen-loadgen/releases/download/v0.1.0/aforo-loadgen_Darwin_x86_64.tar.gz"
      sha256 "878cb341fb78c1e0687d164a77eb32c8f7d735fc703f295f41765570b15fc8dd"

      define_method(:install) do
        bin.install "aforo-loadgen"
        pkgshare.install "scenarios"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aforoai/aforo-nextgen-loadgen/releases/download/v0.1.0/aforo-loadgen_Darwin_arm64.tar.gz"
      sha256 "d26b0a3aaa182e07a7eae319a1070bc7b611c41ba9dfcb984956bed547eb600e"

      define_method(:install) do
        bin.install "aforo-loadgen"
        pkgshare.install "scenarios"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aforoai/aforo-nextgen-loadgen/releases/download/v0.1.0/aforo-loadgen_Linux_x86_64.tar.gz"
      sha256 "f53d5144a8f69ce5fb4ddbfc64dfecfd6713dbd044f2eca0dc0add38ee870b7c"
      define_method(:install) do
        bin.install "aforo-loadgen"
        pkgshare.install "scenarios"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aforoai/aforo-nextgen-loadgen/releases/download/v0.1.0/aforo-loadgen_Linux_arm64.tar.gz"
      sha256 "a55d3b597974dd8e8d495c4000ea718e4434155afa8ad7df3b69839650a2c8fc"
      define_method(:install) do
        bin.install "aforo-loadgen"
        pkgshare.install "scenarios"
      end
    end
  end

  test do
    assert_match "aforo-loadgen v#{version}", shell_output("#{bin}/aforo-loadgen version")
  end
end
